### ISSUE TITLE
Breaks on invalid geojson

### ISSUE THREAD

**Issue by hackergrrl** [digidem/osm-p2p-vector-tile-index#5]
e.g. on a `LineString` with an empty `coordinates` array:

```
/tmp/veccc/node_modules/geojson-vt/src/simplify.js:18
    points[first][2] = 1;
                     ^

TypeError: Cannot set property '2' of undefined
    at simplify (/tmp/veccc/node_modules/geojson-vt/src/simplify.js:18:22)
    at project (/tmp/veccc/node_modules/geojson-vt/src/convert.js:88:9)
    at convertFeature (/tmp/veccc/node_modules/geojson-vt/src/convert.js:47:47)
    at convert (/tmp/veccc/node_modules/geojson-vt/src/convert.js:15:13)
    at new GeoJSONVT (/tmp/veccc/node_modules/geojson-vt/src/index.js:24:20)
    at geojsonvt (/tmp/veccc/node_modules/geojson-vt/src/index.js:13:12)
    at /tmp/veccc/node_modules/osm-p2p-vector-tile-index/index.js:102:32
    at /tmp/veccc/node_modules/osm-p2p-vector-tile-index/index.js:114:35
    at /tmp/veccc/node_modules/osm-p2p-geojson/index.js:50:7
    at f (/tmp/veccc/node_modules/once/once.js:25:25)
```

**Comment by hackergrrl** [comment]
Fixed thanks to `osm-p2p-geojson@3.0.0`, which does GeoJSON hinting and filters malformed documents.
